#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

alias t='clear;task calendar;task list'
alias gotoscripts="cd ~/Documents/repos/myLinuxRepo/scripts"
alias gotoblog="cd ~/Documents/repos/serolrom.github.io"
export PATH="~/Documents/repos/scripts:$PATH"


